config/routes.rb
Triage::Application.routes.draw do
  require File.expand_path("../../lib/custom_constraints", __FILE__)
  devise_for :database_users, :directory_users, skip: [:sessions]

  devise_scope :database_user do
    get 'sign_in' => 'sessions#new', :as => :new_session
    post 'sign_in' => 'sessions#create', :as => :create_session
    delete 'sign_out' => 'sessions#destroy', :as => :destroy_session
  end

  # Assignment routes. These are really just requests, but with some filters.
  scope 'assignments' do
    get 'open' => 'requests#open_assignments', :as => 'open_assignments'
    get 'closed' => 'requests#closed_assignments', :as => 'closed_assignments'
  end

  resources :requests do
    get 'open', :on => :collection
    get 'closed', :on => :collection
    get 'unassigned', :on => :collection
    get 'search', :on => :collection
    resources :comments, :only => [:create]
    resources :attachments, :only => [:create, :destroy]
  end

  scope 'settings' do
    get 'profile' => 'settings#edit_profile', as: 'edit_profile'
    put 'profile' => 'settings#update_profile', as: 'update_profile'
    get 'password' => 'settings#edit_password', as: 'edit_password'
    put 'password' => 'settings#update_password', as: 'update_password'
  end
  
  mount Notifier::Preview => 'mail_view' if Rails.env.development?

  get '/', to: 'requests#unassigned', constraints: RoleConstraint.new('administrator')
  get '/', to: 'requests#open_assignments', constraints: RoleConstraint.new('provider')
  get '/', to: 'requests#open'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!

  def edit_profile
    authorize! :update, current_user
  end

  def update_profile
    authorize! :update, current_user

    if current_user.update_attributes profile_params
      flash.now[:notice] = t 'settings.update_profile.success'
    end

    render 'edit_profile'
  end

  def edit_password
    authorize! :update, current_user
  end

  def update_password
    authorize! :update, current_user

    # Confirm password.
    if params[:user][:password] != params[:user][:password_confirmation]
      flash.now[:error] = t 'settings.update_password.mismatch'
    elsif current_user.update_attributes password_params
      flash.now[:notice] = t 'settings.update_password.success'
    end

    render 'edit_password'
  end

  def profile_params
    return params.require(:user).permit(:name, :email, :available)
  end

  def password_params
    return params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/setting_helper.rb
module SettingHelper
  def display_password_form?
    current_user.is_a? DatabaseUser
  end
end

app/views/settings/_nav.html.haml
- content_for :nav do
  %nav
    %ul
      %li.header
        = t 'nav.settings'
      %li{ class: ('active' if (params[:controller] == 'settings' && (params[:action] == 'edit_profile' || params[:action] == 'update_profile'))) }
        = link_to edit_profile_path do
          = t 'nav.profile'
      %li{ class: ('active' if (params[:controller] == 'settings' && (params[:action] == 'edit_password' || params[:action] == 'update_password'))) }
        = link_to edit_password_path do
          = t 'nav.password'

app/views/settings/edit_password.html.haml
= render 'nav'

- if display_password_form?
  .box
    = simple_form_for current_user, as: :user, url: update_password_path do |f|
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit, class: 'btn-primary', value: t('settings.edit_password.update_password')
- else
  .alert
    = t '.password_managed_externally'

app/views/settings/edit_profile.html.haml
= render 'nav'

.box
  = simple_form_for current_user, as: :user, url: update_profile_path do |f|
    = f.input :email
    = f.input :name
    = f.input :available
    = f.button :submit, class: 'btn-primary', value: t('settings.edit_profile.update_profile')