config/routes.rb
Triage::Application.routes.draw do
  require File.expand_path("../../lib/custom_constraints", __FILE__)
  devise_for :database_users, :directory_users, skip: [:sessions]

  devise_scope :database_user do
    get 'sign_in' => 'sessions#new', :as => :new_session
    post 'sign_in' => 'sessions#create', :as => :create_session
    delete 'sign_out' => 'sessions#destroy', :as => :destroy_session
  end

  # Assignment routes. These are really just requests, but with some filters.
  scope 'assignments' do
    get 'open' => 'requests#open_assignments', :as => 'open_assignments'
    get 'closed' => 'requests#closed_assignments', :as => 'closed_assignments'
  end

  resources :requests do
    get 'open', :on => :collection
    get 'closed', :on => :collection
    get 'unassigned', :on => :collection
    get 'search', :on => :collection
    resources :comments, :only => [:create]
    resources :attachments, :only => [:create, :destroy]
  end

  scope 'settings' do
    get 'profile' => 'settings#edit_profile', as: 'edit_profile'
    put 'profile' => 'settings#update_profile', as: 'update_profile'
    get 'password' => 'settings#edit_password', as: 'edit_password'
    put 'password' => 'settings#update_password', as: 'update_password'
  end
  
  mount Notifier::Preview => 'mail_view' if Rails.env.development?

  get '/', to: 'requests#unassigned', constraints: RoleConstraint.new('administrator')
  get '/', to: 'requests#open_assignments', constraints: RoleConstraint.new('provider')
  get '/', to: 'requests#open'
end

app/views/layouts/_footer.html.haml
.row
  .col-md-8.col-md-offset-2.right.footer
    %hr
    %small
      &copy; 2013 Jordan MacDonald

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Triage
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{rel: "shortcut icon", href: "/favicon.ico"}
  %body
    .navbar.navbar-default.navbar-static-top{ role: 'navigation' }
      .navbar-inner
        %a.navbar-brand{ :href => '#' } Triage
        - if current_user
          %ul.nav.navbar-nav
            %li{:class => ('active' if (params[:controller] == 'requests' and params[:action] != 'new'))}
              = link_to t('navbar.requests'), requests_path
            %li{:class => ('active' if current_page?(new_request_path))}
              = link_to t('navbar.new_request'), new_request_path
            - unless current_user.role == 'requester'
              = form_tag(search_requests_path, class: 'navbar-form navbar-left', method: 'get', id: 'quick_search', role: 'search') do
                .form-group
                  = text_field_tag 'request_id', nil, placeholder: 'Request #', class: 'form-control'
                %button.btn.btn-default{type: 'submit'}
                  Search
          %ul.nav.navbar-nav.pull-right
            %li{:class => ('active' if (params[:controller] == 'settings'))}
              = link_to t('navbar.settings'), edit_profile_path
            %li
              = link_to t('navbar.logout'), destroy_session_path, :method => :delete
        - else
          %ul.nav.navbar-nav.pull-right
            %li
              = link_to t('navbar.login'), new_user_session_path
    .container
      .row
        .col-md-2
          = yield :nav
        .col-md-7
          / Flash messages
          - if flash[:notice]
            .alert.alert-info
              = flash[:notice]
          - if flash[:alert]
            .alert.alert-error
              = flash[:alert]
          - if flash[:error]
            .alert.alert-error
              = flash[:error]
          = yield
        .col-md-3
          = yield :sidebar

app/views/layouts/devise.html.haml
!!! 5
%html
  %head
    %title Triage
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-8.col-md-offset-2
          / Flash messages
          - if flash[:notice]
            .alert.alert-info
              = flash[:notice]
          - if flash[:alert]
            .alert.alert-error
              = flash[:alert]
          - if flash[:error]
            .alert.alert-error
              = flash[:error]
      = yield
      = render 'layouts/footer'

app/views/layouts/notifier.html.haml
!!! 5
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    = stylesheet_link_tag 'notifier'
  %body
    .container
    = yield
    .row
      .col-md-6.col-md-offset-3.center
        %hr
        Click #{link_to 'here', @url} to view the request.

app/views/layouts/request_mailer.html.haml
!!! 5
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    = stylesheet_link_tag 'mailer'
  %body
    = yield